name: API Test
# This workflow continously runs the API Tests for this project twice a day, in order to check, if the remote API is still compatible with this tool.
# If the MFA token of the account expires, this workflow can be executed manually in order to acquire a new token.

on:
  schedule:
    - cron: '5 5,17 * * *'
  workflow_dispatch:

env:
  PKG_NAME: icloud-photos-sync
  NODE_VERSION: 18
  APPLE_ID_USER: ${{ secrets.TEST_APPLE_ID_USER }}
  APPLE_ID_PWD: ${{ secrets.TEST_APPLE_ID_PWD }}
  PORT: 8080
  LOG_TO_CLI: true
  NODE_OPTIONS: --experimental-vm-modules

jobs:
  run-test:
    name: Run Test
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    env:
      TRUST_TOKEN: ${{ secrets.TEST_TRUST_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Build & Install
      run: |
        npm run clean && \
        npm install && \
        npm run build && \
        npm link
      working-directory: rootfs/opt/icloud-photos-sync/
    - name: Check MFA Token
      run: |
        icloud-photos-sync token
      env:
        FAIL_ON_MFA: true
    - name: Run API Test
      run: |
        npm run test-api
      working-directory: rootfs/opt/icloud-photos-sync/
  
  acquire-token:
    name: Acquire Token
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Build 
      run: |
        npm run clean && \
        npm install && \
        npm run build
      working-directory: rootfs/opt/icloud-photos-sync/
    - name: Install
      run: |
        npm link && \
        chmod +x ~/work/icloud-photos-sync/icloud-photos-sync/rootfs/root/enter_mfa.sh && \
        ln -s ~/work/icloud-photos-sync/icloud-photos-sync/rootfs/root/enter_mfa.sh /usr/local/bin/enter_mfa && \
        chmod +x ~/work/icloud-photos-sync/icloud-photos-sync/rootfs/root/resend_mfa.sh && \
        ln -s ~/work/icloud-photos-sync/icloud-photos-sync/rootfs/root/resend_mfa.sh /usr/local/bin/resend_mfa
      working-directory: rootfs/opt/icloud-photos-sync/
    - name: Access runner to acquire token
      uses: lhotari/action-upterm@v1
      with:
        limit-access-to-users: steilerDev
        upterm-server: ssh://uptermd.upterm.dev:22