name: Build & Test
# This reusable workflow will test, build and scan the application. All build assets will be packaged and uploaded
# This action is also run, in order to validate, that Pull Requests are functional
# When this workflow is triggered due to a push to dev, testing will be fast tracked
#
# Creates the following artifacts:
#  - docker-artifacts (Docker RootFS + Dockerfile)
#  - app-artifacts (NPM Upload)
#  - gh-wiki-artifacts (Documentation for GH Wiki) - Only if github.ref != 'refs/heads/dev'
#  - gh-pages (Documentation and webpage for GH Pages) - Only if github.ref != 'refs/heads/dev'
#  - changelog (File containing changelog description) - Only if github.ref != 'refs/heads/dev'
#  - coverage-report (Test coverage report)

# Todo: Add Code Coverage Report to GH Pages & using https://shields.io/endpoint to create badge 

on:
  workflow_call:
  pull_request:
  push: # For any other branch
    branches-ignore:
      - 'main'
      - 'dev'

permissions: {}

jobs:
  build-app:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: 'app/.node-version'
          cache: 'npm'
          cache-dependency-path: app/
      - name: Build app artifacts
        run: |
          npm ci
          npm run build
          true || npm run upload-sourcemap
          cp ../README.md ../CHANGELOG.md ../LICENSE ./
        working-directory: app/
      - name: Upload app artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-artifacts
          path: |
            ./app/.node-version
            ./app/README.md
            ./app/CHANGELOG.md
            ./app/LICENSE
            ./app/package.json
            ./app/package-lock.json
            ./app/bin/

  build-typedoc:
    name: Build TypeDoc
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/dev'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: 'app/.node-version'
          cache: 'npm'
          cache-dependency-path: app/
      - name: Install
        run: npm ci
        working-directory: app/
      - name: Build doc artifacts
        run: npm run doc
        working-directory: app/
      - name: Upload doc artifacts
        uses: actions/upload-artifact@v3
        with:
          name: gh-wiki-artifacts
          path: |
            ./app/README.md
            ./app/CHANGELOG.md
            ./app/LICENSE
            ./app/doc/
  

  build-changelog:
    name: Build Changelog
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/dev'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build changelog artifacts
        run: |
          START_LINE=$(grep -n -m 1 -E '^##' CHANGELOG.md | grep -Eo '^[0-9]+')
          ((START_LINE++))
          END_LINE=$(grep -n -m 2 -E '^##' CHANGELOG.md | tail -n 1 | grep -Eo '^[0-9]+')
          LENGTH=$(( END_LINE - START_LINE ))
          tail -n +$START_LINE CHANGELOG.md | head -n $LENGTH > CHANGELOG.latest.md
      - name: Upload changelog artifact
        uses: actions/upload-artifact@v3
        with:
          name: changelog
          path: ./CHANGELOG.latest.md

  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: build-app
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download app artifacts
        uses: actions/download-artifact@v3
        with:
          name: app-artifacts
          path: ./docker/rootfs/opt/icloud-photos-sync
      - name: Build docker rootfs
        run: |
          # Packaging assets
          tar -C ./rootfs -czf ./rootfs.tar.gz ./
        working-directory: docker/
      - name: Build docker image
        run: |
          docker build ./docker --tag ${{ github.event.repository.name }}
          docker save ${{ github.event.repository.name }} | gzip > ./docker-image.tar.gz
          cp ./docker/.docker-username .
      - name: Upload docker artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docker-artifacts
          path: |
            ./.docker-username
            ./README.md
            ./CHANGELOG.md
            ./LICENSE
            ./docker-image.tar.gz
        
  test-app:
    name: Test App
    strategy:
      matrix:
        os: ${{ fromJSON(github.ref == 'refs/heads/dev' && '["ubuntu-latest"]' || '["ubuntu-latest", "macos-latest"]') }} # Skipping macOS on 'dev' branch, due to slow performance
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: 'app/.node-version'
          cache: 'npm'
          cache-dependency-path: app/
      - name: Install
        run: npm ci
        working-directory: app/
      - name: Test All
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          /usr/bin/env \
          TEST_APPLE_ID_USER=${{ secrets.TEST_USER }} \
          TEST_APPLE_ID_PWD=${{ secrets.TEST_PWD }} \
          TEST_TRUST_TOKEN=${{ secrets.TEST_TRUST_TOKEN }} \
          NODE_NO_WARNINGS=1 \
          node --experimental-vm-modules node_modules/.bin/jest --config jest.config.json
        env:
          NODE_OPTIONS: --experimental-vm-modules # Needed for JEST / ESM compatibility
          NODE_NO_WARNINGS: 1
          TEST_APPLE_ID_USER: ${{ secrets.TEST_USER }}
          TEST_APPLE_ID_PWD: ${{ secrets.TEST_PWD }}
          TEST_TRUST_TOKEN: ${{ secrets.TEST_TRUST_TOKEN }}
        working-directory: app/
      - name: Test Unit Only
        if: ${{ github.ref != 'refs/heads/main' }}
        run: npm run test
        env:
          NODE_OPTIONS: --experimental-vm-modules # Needed for JEST / ESM compatibility
        working-directory: app/
      - name: Collect test coverage
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: |
            app/coverage/

  test-docker:
    name: Test Docker Image
    needs: build-docker
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/dev'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download 
        uses: actions/download-artifact@v3
        with:
          name: docker-artifacts
          path: docker-image
      - name: Install
        run: docker load --input ./docker-image/docker-image.tar.gz
      - name: Prepare tests
        run: chmod +x ./docker/test/*
      - name: Test Image
        run: run-parts -v --exit-on-error ./docker/test

  build-gh-pages:
    name: Build GH Pages
    needs: test-app
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/dev'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' 
          cache-dependency-path: pages/
      - name: Setup build environment
        run: |
          pip install -r pages/requirements.txt
          cp LICENSE README.md CHANGELOG.md pages/docs/
      - name: Build Pages
        run: mkdocs build
        working-directory: pages/
      - name: Bundle coverage reports
        uses: actions/download-artifact@v3
        with:
          name: coverage-report
          path: ./pages/site/dev/coverage
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./pages/site/